sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t sravanthikare/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sravanthikare/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-368906956760"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_AccessKey
  secure_access_key: $AWS_SecretKey