sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t sravanthikare/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sravanthikare/docker-react npm run test -- -- coverage
  - q